site_name: HADeploy

pages:
- Home: index.md
- Installation: installation.md
- "Getting started": gettingstarted.md
- "Plugins reference":
  - Inventory: 
    - plugins_reference/inventory/ansible_inventory_files.md
    - plugins_reference/inventory/hosts.md
  - Files:
    - plugins_reference/files/folders.md
- Architecture: architecture.md

#theme: readthedocs
#theme: mkdocs
theme: 'material'
#theme: yeti  # Bootswatch
#theme: bootstrap
