site_name: HADeploy

pages:
- Home: index.md
- Installation: installation.md
- "Getting started": gettingstarted.md
- References:
  - "Ansible_inventory: ansible_inventory_files": plugins_reference/ansible_inventory/ansible_inventory_files.md
  - "Files: folders": plugins_reference/files/folders.md
  - "Inventory: hosts": plugins_reference/inventory/hosts.md
  - "Inventory: host_overrides": plugins_reference/inventory/host_overrides.md
  - "Inventory: host_groups": plugins_reference/inventory/host_groups.md
  - "Users: users": plugins_reference/users/users.md
  - "Users: groups": plugins_reference/users/groups.md
- "Plugins reference":
  - Ansible_inventory:
    - ansible_inventory_files: plugins_reference/ansible_inventory/ansible_inventory_files.md
  - Files:
    - folders: plugins_reference/files/folders.md
  - Inventory: 
    - hosts: plugins_reference/inventory/hosts.md
    - host_overrides: plugins_reference/inventory/host_overrides.md
    - host_groups: plugins_reference/inventory/host_groups.md
  - Users:
    - "users": plugins_reference/users/users.md
    - "groups": plugins_reference/users/groups.md

- Architecture: architecture.md

#theme: readthedocs
theme: mkdocs
#theme: 'material'
#theme: yeti  # Bootswatch
#theme: bootstrap
