site_name: HADeploy

pages:
- Home: index.md
- Installation: installation.md
- "Getting started":
  - "First step": getting_started/first_step.md
  - "Next step": getting_started/next_step.md
- "Plugins reference":
  - Core:
    - encrypted_vars: plugins_reference/core/encrypted_vars.md
    - excluded_scopes: plugins_reference/core/excluded_scopes.md
    - include: plugins_reference/core/include.md
    - included_scopes: plugins_reference/core/included_scopes.md
    - vars: plugins_reference/core/vars.md
  - Ansible:
    - Overview:  plugins_reference/ansible/ansible_overview.md
    - ansible_playbooks: plugins_reference/ansible/ansible_playbooks.md
    - playbooks_folders: plugins_reference/ansible/playbooks_folders.md
    - roles_folders: plugins_reference/ansible/roles_folders.md
  - Ansible_inventories:
    - ansible_inventories: plugins_reference/ansible_inventories/ansible_inventories.md
  - Files:
    - files: plugins_reference/files/files.md
    - folders: plugins_reference/files/folders.md
    - maven_repositories: plugins_reference/files/maven_repositories.md
    - local_files_folders: plugins_reference/files/local_files_folders.md
    - local_templates_folders: plugins_reference/files/local_templates_folders.md
    - trees: plugins_reference/files/trees.md
  - HBase:
    - hbase_datasets: plugins_reference/hbase/hbase_datasets.md
    - hbase_namespaces: plugins_reference/hbase/hbase_namespaces.md
    - hbase_relay: plugins_reference/hbase/hbase_relay.md
    - hbase_tables: plugins_reference/hbase/hbase_tables.md
  - Hdfs:
    - hdfs_relay: plugins_reference/hdfs/hdfs_relay.md
    - source_host_credentials: plugins_reference/hdfs/source_host_credentials.md
  - Hive:
    - hive_databases: plugins_reference/hive/hive_databases.md
    - hive_relay: plugins_reference/hive/hive_relay.md
    - hive_tables: plugins_reference/hive/hive_tables.md
  - Inventory: 
    - "exit_on_fail": plugins_reference/inventory/exit_on_fail.md
    - hosts: plugins_reference/inventory/hosts.md
    - host_groups: plugins_reference/inventory/host_groups.md
    - host_group_overrides: plugins_reference/inventory/host_group_overrides.md
    - host_overrides: plugins_reference/inventory/host_overrides.md
  - Kafka:
    - kafka_relay: plugins_reference/kafka/kafka_relay.md
    - kafka_topic: plugins_reference/kafka/kafka_topics.md
  - Systemd:
    - systemd_units: plugins_reference/systemd/systemd_units.md
  - Supervisors:
    - Overview: plugins_reference/supervisor/supervisor_overview.md
    - supervisors: plugins_reference/supervisor/supervisors.md
    - supervisor_programs: plugins_reference/supervisor/supervisor_programs.md
  - Ranger:
    - hbase_ranger_policies: plugins_reference/ranger/hbase_ranger_policies.md
    - hdfs_ranger_policies: plugins_reference/ranger/hdfs_ranger_policies.md
    - hive_ranger_policies: plugins_reference/ranger/hive_ranger_policies.md
    - kafka_ranger_policies: plugins_reference/ranger/kafka_ranger_policies.md
    - ranger_relay: plugins_reference/ranger/ranger_relay.md
    - yarn_ranger_policies: plugins_reference/ranger/yarn_ranger_policies.md
  - Users:
    - "groups": plugins_reference/users/groups.md
    - "users": plugins_reference/users/users.md
- More:
  - "Under the hood": more/under_the_hood.md
  - "Execution order": more/execution_order.md
  - "Altering scope": more/altering_scope.md
  - "Secured cluster": more/secured_cluster.md
  - "YAML tricks": more/yaml_tricks.md
  - "Release notes": more/release_notes.md

#theme: readthedocs
theme: mkdocs
#theme: 'material'
#theme: yeti  # Bootswatch
#theme: cosmo
#theme: bootstrap
