site_name: HADeploy

pages:
- Home: index.md
- Installation: installation.md
- "Getting started": gettingstarted.md
- "Plugins reference":
  - Core:
    - include: plugins_reference/core/include.md
    - vars: plugins_reference/core/vars.md
  - Ansible_inventory:
    - ansible_inventory_files: plugins_reference/ansible_inventory/ansible_inventory_files.md
  - Files:
    - files: plugins_reference/files/files.md
    - folders: plugins_reference/files/folders.md
    - local_files_folders: plugins_reference/files/local_files_folders.md
    - local_templates_folders: plugins_reference/files/local_templates_folders.md
    - trees: plugins_reference/files/trees.md
  - HBase:
    - hbase_datasets: plugins_reference/hbase/hbase_datasets.md
    - hbase_namespaces: plugins_reference/hbase/hbase_namespaces.md
    - hbase_relay: plugins_reference/hbase/hbase_relay.md
    - hbase_tabless: plugins_reference/hbase/hbase_tables.md
  - Hdfs:
    - hdfs_relay: plugins_reference/hdfs/hdfs_relay.md
    - source_host_credentials: plugins_reference/hdfs/source_host_credentials.md
  - Inventory: 
    - hosts: plugins_reference/inventory/hosts.md
    - host_groups: plugins_reference/inventory/host_groups.md
    - host_group_overrides: plugins_reference/inventory/host_group_overrides.md
    - host_overrides: plugins_reference/inventory/host_overrides.md
  - Kafka:
    - kafka_relay: plugins_reference/kafka/kafka_relay.md
    - kafka_topic: plugins_reference/kafka/kafka_topics.md
  - Ranger:
    - hbase_ranger_policies: plugins_reference/ranger/hbase_ranger_policies.md
    - hdfs_ranger_policies: plugins_reference/ranger/hdfs_ranger_policies.md
    - kafka_ranger_policies: plugins_reference/ranger/kafka_ranger_policies.md
    - ranger_relay: plugins_reference/ranger/ranger_relay.md
  - Users:
    - "users": plugins_reference/users/users.md
    - "groups": plugins_reference/users/groups.md

- Architecture: architecture.md

#theme: readthedocs
#theme: mkdocs
theme: 'material'
#theme: yeti  # Bootswatch
#theme: bootstrap

unused:
- References:
  - "Ansible_inventory: ansible_inventory_files": plugins_reference/ansible_inventory/ansible_inventory_files.md
  - "Files: folders": plugins_reference/files/folders.md
  - "Inventory: hosts": plugins_reference/inventory/hosts.md
  - "Inventory: host_overrides": plugins_reference/inventory/host_overrides.md
  - "Inventory: host_groups": plugins_reference/inventory/host_groups.md
  - "Users: users": plugins_reference/users/users.md
  - "Users: groups": plugins_reference/users/groups.md
